### ISSUE TITLE
Move Deployment.action* methods to UnitSentry?

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/amulet#133]
...so you'd call it like `self.d.sentry['service'][0].action_do('foo')`
instead of `self.d.action_do(self.d.sentry['service'][0].info['unit_name'], 'foo')`

Keep the old methods (on Deployment) but issue a DeprecationWarning and remove at next major version bump.

**Comment by marcoceppi** [comment]
We should align more with the juju2 terminology if we do this, so
`self.d.sentry['service'][0].run_action('foo')` this also solves some of
the work outlined in Amulet 2.0 roadmap

**Comment by tvansteenburgh** [comment]
Yeah, for completeness, here are the aliases we need:

```
list_actions = action_defined
run_action = action_do
show_action_output = action_fetch
```

**Comment by tvansteenburgh** [comment]
Here's what I propose we'll end up with:

```python
Deployment.action_defined (deprecated)
Deployment.action_do (deprecated)
Deployment.get_action_output = Deployment.action_fetch  # I think 'get_' makes more sense than 'show_'

UnitSentry.action_defined = UnitSentry.list_actions
UnitSentry.action_do = UnitSentry.run_action
```

@marcoceppi @johnsca Sound good?

**Comment by marcoceppi** [comment]
:+1:
