### ISSUE TITLE
Does configure wait?

### ISSUE THREAD

**Issue by galgalesh** [juju/amulet#167]
1. Does `configure` wait until `config-changed` hook exits? The documentation doesn't seem to answer this question.
2. Why do I get this strange behavior?

 Following code snippet:

```python
        self.d.configure('openvpn', {
            'port': 1194,
            'protocol': 'udp',
            'push-default-gateway': False,
            'push-dns': False,
        })
        sleep(2)
        confcont = self.unit.file_contents('/home/ubuntu/client1.ovpn')
```

If I remove the `sleep` statement, there is a possibility that I get the previous config. This seems strange to me since `file_contents` uses `juju run` in the backend which is part of the lifecycle (it should only run after config-changed exits).

**Comment by tvansteenburgh** [comment]
`configure` just shells out to `juju config` and then returns. The question is, if you do this...

    juju config ...
    juju run ...

...is it possible for the `juju run` command to see the charm in its state *prior* to the `juju config` call?

@mitechie told me that in the above scenario, the config-changed hook is guaranteed to finish before the `juju run` command is executed.

This leaves me confused as to why your `sleep(2)` would be necessary, unless the logic of your hook code (which I haven't looked at) is such that the changes to `client1.ovpn` may not be written until sometime after the hook has finished? Seems unlikely, but possible I guess?
