### ISSUE TITLE
Uncommitted changes in git charms are not copied to the deployed version

### ISSUE THREAD

**Issue by bac** [juju/amulet#73]
When deploying our charm we construct a 'fat charm' payload by creating a 'files' subdirectory and putting a tarball in it. These files are not included in the charm passed to the deployer.

The old behavior of copying the tree to a new spot and initializing it as a bzr branch did not have this restriction and worked nicely. I suspect doing more in place is the reason for #55 too.

In our instance we never want those files checked in, so the work-around of just checking things in before starting (if you remember) doesn't work.

**Comment by tvansteenburgh** [comment]
Fixed by 6a15ee16450f9523c5068b9f70594764762905d2
